#! /bin/bash



# Converts all files from one extension to another as specified in the arguments



if [[ $# -ne 2 ]]; then
	printf "\nYou are expected to supply 2 arguments.\n"

else
	for file in *"$1"; do
		base=$(basename "${file}" "${1}")
		mv "${file}" "${base}${2}"
	done
fi
exit 0
