#! /bin/bash

searchhistory="${HOME}/search-history.txt"

if [[ $# -eq 1 && $1 == 'search-history' ]]; then
	cat "${searchhistory}"
	exit 0
fi

echo $* >>"${searchhistory}"
open "https://www.google.com/search?q=$*"
