#! /bin/bash

NOW=$(date "+%Y-%m-%d: %H: %M: %S")
GREEN="\033[0;92m"
FILE_PATH=${HOME}/notes.txt

if [[ $# -eq 1 ]]; then
	if [[ $1 == 'list' ]]; then
		if [[ -f $FILE_PATH ]]; then
			num_notes=$(wc -l <"${FILE_PATH}")
			echo YOU HAVE ${num_notes} NOTES.
			echo '-----------------'
			echo ''
			cat $FILE_PATH
			echo ''
			exit 0
		else
			echo ''
			echo Note list empty!!
			echo ''
			echo Type \'note\' to start adding notes.
			echo ""
			exit 0
		fi
	fi
fi

read -p 'Enter note> ' note

if [[ $note ]]; then
	echo "[${NOW}] ${note}" >>"${FILE_PATH}"
	echo -e "${GREEN}✔ saved:: ${note}"
else
	echo You can\'t save an empty note.
fi

exit 0
