#! /bin/bash


now=`date "+%Y-%m-%d: %H: %M: %S"`
filepath=${HOME}/notes.txt

if [[ $# -eq 1 ]]; then

	if [[ $1 == 'list' ]]; then
		if [[ -f $filepath ]]; then
			num_notes=$(wc -l < "${filepath}")
			echo YOU HAVE ${num_notes} NOTES.
			echo '-----------------'
			echo ''
			cat $filepath
			echo ''
			exit 0
		else
			echo ''
			echo Note list empty!!
			echo ''
			echo Type \'note\' to start adding notes.
			echo ""
			exit 0
		fi
	fi

fi

read -p 'Enter note :: ' note

if [[ $note ]]; then

	echo "[${now}] ${note}" >> "${filepath}"
	echo "[Saved ✔] ${note}"
	
else

	echo You can\'t save an empty note.

fi

exit 0
