#! /bin/bash


# A game which generates a random number and allows the user to guess what the number is
# It gives hints when the player misses the number


guessed=$(($RANDOM % 100))
count=0
my_guess=

until [[ my_guess -eq guessed ]]; do
	
	((count++))
	read -p "Enter your guess> " my_guess
	
	if [[ my_guess -gt guessed ]]; then
		echo ""
		echo "Your target is LESS than ${my_guess}."
		echo ""
	elif [[ my_guess -lt guessed ]]; then
		echo ""
		echo "Your target is GREATER than ${my_guess}."
		echo ""
	else

		if [[ count -lt 3 || count -eq 3 ]]; then
			feedback="  Wow!! Unbelievable \\(◎o◎)/            "
		elif [[ count -gt 3 && count -lt 7 ]]; then
			feedback="  Well, Not so bad. Way to go!          "
		else
			feedback="  Not so impressive ( ͡° ͜ʖ ͡°).           "
		fi
		echo "+----------------------------------------+"
		echo "|  You guessed the number. Yasssssss!!!  | "
		echo "|  Took you ${count} tries.                     | "
		echo "|${feedback}|"
		echo "+----------------------------------------+"
	fi
done
