#! /bin/bash


# A game which generates a random number and allows the user to guess what the number is
# It gives hints when the player misses the number


guessed=$(($RANDOM % 100))
count=0
what_user_guesses=

until [[ what_user_guesses -eq guessed ]]; do
		
	((count++))
	read -p "Enter your guess> " what_user_guesses
	
	if [[ $what_user_guesses =~ ^[0-9]+$ ]]; then
		
		if [[ what_user_guesses -gt guessed ]]; then
			echo ""
			echo "Your target is LESS than ${what_user_guesses}."
			echo ""
		elif [[ what_user_guesses -lt guessed ]]; then
			echo ""
			echo "Your target is GREATER than ${what_user_guesses}."
			echo ""
		else

			if [[ count -lt 3 || count -eq 3 ]]; then
				feedback="  Wow!! Unbelievable \\(◎o◎)/            "
			elif [[ count -gt 3 && count -lt 7 ]]; then
				feedback="  Well, Not so bad. Way to go!          "
			else
				feedback="  Not so impressive ( ͡° ͜ʖ ͡°).           "
			fi
			echo "+----------------------------------------+"
			echo "|  You guessed the number. Yasssssss!!!  | "
			echo "|  Took you ${count} tries.                     | "
			echo "|${feedback}|"
			echo "+----------------------------------------+"
		fi
	
	else
		
		echo ""
		echo "Invalid Input.. Number Expected"
		echo ""
	fi
done

exit 0
